### ISSUE TITLE
Kan ej importera efter att ha laddat upp ny version

### ISSUE THREAD

**Issue by tobbee** [Scouterna/skojjt#138]
Efter att ha byggt om skojjt och ladda upp den på Google App Engine så går det inte längre att importera.

Fungerade inte på GAE/master men inte heller då jag gick tillbaks till master utan jag fick liknande fel, se nedan när jag försökte impotera vår kår. Däremot fungerar det när jag kör lokalt på dev_appserver.py.

Nedanstående är felmeddelandet jag får i browsern när jag försöker uppdatera baserat på master.

Vore tacksam för hjälp att komma vidare.

POST, ImmutableMultiDict([('firmatecknartelefon', u'xxx'), ('apikey_all_members', u'xxxxxx'), ('kommunID', u'1480'), ('telefon', u''), ('firmatecknare', u'Torbj\xf6rn Einarsson'), ('bankkonto', u''), ('epost', u''), ('postadress', u'112 60 Stockholm'), ('scoutnetID', u'740'), ('organisationsnummer', u'802007-4756'), ('foreningsID', u'1135'), ('apikey_waitinglist', u'xxxx), ('import', u'Spara och Starta import'), ('lagerplats', u'M\xe5rten Triewalds Malmg\xe5rd'), ('adress', u'Gj\xf6rwellsgatan 29'), ('attendance_min_year', u'15')])

Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/f26c7186b0a736e8/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 271, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/data/home/apps/e~stg-skojjt/20210205t233116.432869440377126797/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/base/data/home/apps/e~stg-skojjt/20210205t233116.432869440377126797/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/base/data/home/apps/e~stg-skojjt/20210205t233116.432869440377126797/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/base/data/home/apps/e~stg-skojjt/20210205t233116.432869440377126797/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/base/data/home/apps/e~stg-skojjt/20210205t233116.432869440377126797/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/base/data/home/apps/e~stg-skojjt/20210205t233116.432869440377126797/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/base/data/home/apps/e~stg-skojjt/20210205t233116.432869440377126797/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/base/data/home/apps/e~stg-skojjt/20210205t233116.432869440377126797/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/base/data/home/apps/e~stg-skojjt/20210205t233116.432869440377126797/scoutgroupinfo.py", line 45, in show
    return startAsyncImport(scoutgroup.apikey_all_members, scoutgroup.scoutnetID, Semester.getOrCreateCurrent().key, user, request)
  File "/base/data/home/apps/e~stg-skojjt/20210205t233116.432869440377126797/imports.py", line 69, in startAsyncImport
    deferred.defer(importTask, api_key, groupid, semester_key, taskProgress.key, user.key)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/f26c7186b0a736e8/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 275, in defer
    return task.add(queue, transactional=transactional)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/f26c7186b0a736e8/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 1283, in add
    return self.add_async(queue_name, transactional).get_result()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/f26c7186b0a736e8/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 615, in get_result
    return self.__get_result_hook(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/f26c7186b0a736e8/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 2232, in ResultHook
    raise exception
UnknownQueueError

**Comment by martin-green** [comment]
Det ser ut som om att kö-namnet är fel.
Prova: `gcloud app deploy queue.yaml`

**Comment by martin-green** [comment]
Du kan se vilka kö:er som servern har:
https://console.cloud.google.com/cloudtasks

**Comment by tobbee** [comment]
Det hjälpte att köra `gcloud app deploy queue.yaml`.
Vore bra att få med denna rad i README.md.

**Comment by tobbee** [comment]
Det funkar att importera, men när jag ändrar koden importdata.py körs fortfarande gammal kod (jag har en gammal omskrivning av kårnamn som jag nu vill ta bort när det finns möjlighet att flytta en termin i taget). Koden är dock uppladdad för jag ser saker som jag ändrat på skärmen för vanliga sidor. Kollar jag på versioner i konsolen är det det senaste som körs vilket också stämmer med att andra saker uppdaterats. Är det något speciellt med koden som kör i import-kön så att man måste starta om denna kö, eller finns det någon annan anledning att gammal kod körs?

**Comment by tobbee** [comment]
Fungerade till slut utan att jag gjort något speciellt, så nu har jag migrerat kåren till nytt namn.  Den gamla kåren har dock inte försvunnit ännu trots att jag försökt ta bort den och det är där man hamnar av default. Kan hända att några användardata  är kvar i en cache, för enligt databasen är användarna bara med i den nya kåren. Att döda instansen räckte inte för att det skulle ändras, så det finns kanske en annan cache någonstans. Får se om det funkar imorgon. Annars får det bli en ny ticket.
